[project]
authors = ["@theausicist"]
entry = "main.sw"
license = "Apache-2.0"
name = "mock-vault-pricefeed"

[dependencies]
helpers = { path = "../../helpers" }
mock_interfaces = { path = "../interfaces" }
