[project]
authors = ["@theausicist"]
entry = "main.sw"
license = "Apache-2.0"
name = "vault-pricefeed"

[dependencies]
core_interfaces = { path = "../interfaces" }
helpers = { path = "../../helpers" }
pyth_interface = { git = "https://github.com/pyth-network/pyth-crosschain", tag = "pyth-lazer-agent-v0.4.1" }
