[project]
authors = ["@theausicist"]
entry = "main.sw"
license = "Apache 2.0"
name = "rlp"

[dependencies]
standards = { git = "https://github.com/FuelLabs/sway-standards", tag = "v0.5.1" }
sway_libs = { git = "https://github.com/FuelLabs/sway-libs", tag = "v0.24.0" }
asset_interfaces = { path = "../interfaces" }
helpers = { path = "../../helpers" }