[project]
authors = ["@theausicist"]
entry = "main.sw"
license = "Apache-2.0"
name = "vault"

[dependencies]
sway_libs = { git = "https://github.com/FuelLabs/sway-libs", tag = "v0.24.0" }
standards = { git = "https://github.com/FuelLabs/sway-standards", tag = "v0.5.1" }
helpers = { path = "../../helpers" }
core_interfaces = { path = "../interfaces" }
asset_interfaces = { path = "../../assets/interfaces" }