[project]
authors = ["@theausicist"]
entry = "main.sw"
license = "Apache 2.0"
name = "fungible"

[dependencies]
src20 = "0.8.0"
src3  = "0.8.0"
fungible_abi = { path = "../fungible-abi" }
helpers = { path = "../../helpers" }