[project]
authors = ["@theausicist"]
entry = "main.sw"
license = "Apache-2.0"
name = "rlp-manager"

[dependencies]
src3 = "0.8.0"
helpers = { path = "../../helpers" }
core_interfaces = { path = "../interfaces" }
asset_interfaces = { path = "../../assets/interfaces" }

[proxy]
enabled = true
address = "0x5b210f226d57696d3d0fbf9c85e1232a045d50c12743d1b2cdbab17134eb80a9"
