[project]
authors = ["@theausicist"]
entry = "main.sw"
license = "Apache 2.0"
name = "rusd"

[dependencies]
src20 = "0.8.0"
src3 = "0.8.0"
asset = "0.26.1"
asset_interfaces = { path = "../interfaces" }
helpers = { path = "../../helpers" }